(()=>{'use strict';
const S=window.HNBH_PINYIN_SOURCES,D=window.HNBH_PINYIN,A=window.HNBH_PINYIN_AUDIO,$=id=>document.getElementById(id),key='hnbh_pinyin_review_v1';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ids=new Set([...S.videos.map(v=>v.id),'audio']),checks=['watched','mouthOnly','audioClear','pinyinCorrect'];let records={},storageOK=true;
function clean(input){const out={};if(!input||typeof input!=='object'||Array.isArray(input))throw Error('Sai cấu trúc phiếu.');for(const [id,r]of Object.entries(input)){if(!ids.has(id)||!r||typeof r!=='object'||Array.isArray(r))continue;const x={status:['pending','approved','rejected'].includes(r.status)?r.status:'pending',notes:typeof r.notes==='string'?r.notes.slice(0,10000):'',updated:typeof r.updated==='string'?r.updated.slice(0,50):''};for(const k of checks)x[k]=r[k]===true;if(x.status==='approved'&&id!=='audio'&&!checks.every(k=>x[k]))x.status='pending';out[id]=x;}return out;}
try{records=clean(JSON.parse(localStorage.getItem(key)||'{}'));}catch{storageOK=false;$('adminStatus').textContent='Không đọc được dữ liệu lưu trên trình duyệt. Bạn vẫn có thể ghi chú và xuất JSON.';}
function persist(){if(!storageOK){$('adminStatus').textContent='Chưa lưu trên trình duyệt; hãy xuất JSON để giữ phiếu.';return;}try{localStorage.setItem(key,JSON.stringify(records));$('adminStatus').textContent='Đã lưu phiếu trên trình duyệt này.';}catch{storageOK=false;$('adminStatus').textContent='Trình duyệt không lưu được; hãy xuất JSON để giữ phiếu.';}}
function fields(id,video){const r=records[id]||{};return `<div class="review-fields" data-record="${id}">${video?checks.map((k,i)=>`<label><input type="checkbox" data-check="${k}" ${r[k]?'checked':''}>${['Đã xem trọn clip','Nội dung chỉ có cận miệng, không có mặt người dẫn','Âm đọc rõ, phù hợp làm mẫu','Pinyin và nội dung đã được đối chiếu'][i]}</label>`).join(''):''}<label>Trạng thái <select data-status><option value="pending" ${!r.status||r.status==='pending'?'selected':''}>Chờ tự kiểm tra</option><option value="approved" ${r.status==='approved'?'selected':''}>Đã duyệt</option><option value="rejected" ${r.status==='rejected'?'selected':''}>Cần thay / sửa</option></select></label><label class="notes">${video?'Ghi chú và mốc thời gian cần xem lại':'Ghi chú âm cụ thể, ví dụ: ma3, ju4'}<textarea data-notes maxlength="10000">${esc(r.notes||'')}</textarea></label></div>`;}
function render(){
 $('videoReviews').innerHTML=S.videos.map(v=>`<article class="review-card"><h3>${esc(v.title)}</h3><dl class="source-meta"><dt>Tác giả / tài khoản</dt><dd>${esc(v.author)}</dd><dt>Tiêu đề gốc</dt><dd lang="zh">${esc(v.original)}</dd><dt>Thời lượng</dt><dd>${esc(v.duration)}</dd><dt>ID nguồn</dt><dd>${v.id}</dd></dl><div class="actions"><a class="button secondary" href="${v.url}" target="_blank" rel="noopener noreferrer">Xem bản nguồn ↗</a><a class="button primary" href="https://open.douyin.com/player/video?vid=${v.id}&autoplay=0" target="_blank" rel="noopener noreferrer">Mở video để duyệt ↗</a></div><p class="small muted" style="margin-top:16px">${esc(v.review)}</p>${fields(v.id,true)}</article>`).join('');
 $('audioReviewFields').innerHTML=fields('audio',false);
}
$('audioSource').innerHTML=`<dl class="source-meta"><dt>Người thu</dt><dd>${esc(S.audio.author)}</dd><dt>Dự án / giấy phép</dt><dd><a href="${S.audio.url}" target="_blank" rel="noopener noreferrer">${esc(S.audio.project)}</a> · ${esc(S.audio.license)}</dd><dt>Số tệp</dt><dd>${S.audio.count.toLocaleString('vi-VN')}</dd></dl><p>${esc(S.audio.review)}</p><p><a href="../audio/pinyin/NOTICE.md">Thông báo tác giả và giấy phép</a> · <a href="../docs/pinyin/audio-manifest.json">Danh mục hash từng tệp</a></p>`;
$('reviewSyllable').innerHTML=D.syllables.map(s=>`<option value="${s.base}">${s.base}</option>`).join('');
$('excludedSources').innerHTML=`<p>${esc(S.excluded.author)} · ${esc(S.excluded.reason)}</p><ul>${S.excluded.ids.map(id=>`<li><a href="https://www.douyin.com/video/${id}" target="_blank" rel="noopener noreferrer">${id}</a></li>`).join('')}</ul>`;
document.addEventListener('change',e=>{const box=e.target.closest('[data-record]');if(!box)return;const id=box.dataset.record,r={status:box.querySelector('[data-status]').value,notes:box.querySelector('[data-notes]').value,updated:new Date().toISOString()};for(const k of checks)r[k]=box.querySelector(`[data-check="${k}"]`)?.checked||false;
 if(r.status==='approved'&&id!=='audio'&&!checks.every(k=>r[k])){r.status='pending';box.querySelector('[data-status]').value='pending';records[id]=r;persist();$('adminStatus').textContent='Đã lưu ghi chú. Hoàn thành bốn mục kiểm tra trước khi đánh dấu video đã duyệt.';}else{records[id]=r;persist();}});
document.addEventListener('input',e=>{if(!e.target.matches('[data-notes]'))return;const box=e.target.closest('[data-record]');records[box.dataset.record]={...records[box.dataset.record],notes:e.target.value,updated:new Date().toISOString()};persist();});
$('listenSample').addEventListener('click',async()=>{const base=$('reviewSyllable').value,tone=Number($('reviewTone').value),audio=$('reviewAudio');audio.pause();audio.src='../'+A[base.replace(/ü/g,'v')+tone];$('sampleStatus').textContent=D.toned(base,tone);try{await audio.play();}catch{$('sampleStatus').textContent='Không phát được tệp âm; kiểm tra đường dẫn hoặc kết nối.';}});
for(const id of ['reviewSyllable','reviewTone'])$(id).addEventListener('change',()=>{$('reviewAudio').pause();$('reviewAudio').removeAttribute('src');$('reviewAudio').load();$('sampleStatus').textContent='Bấm nghe mẫu để kiểm tra âm vừa chọn.';});
$('reviewAudio').addEventListener('error',()=>{$('sampleStatus').textContent='Không tải được tệp âm.';});
$('exportReviews').addEventListener('click',()=>{const blob=new Blob([JSON.stringify({version:1,exported:new Date().toISOString(),records},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='phieu-duyet-phat-am.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('adminStatus').textContent='Đã tạo tệp phiếu duyệt để tải về.';});
$('importReviews').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>200000)throw Error('Tệp quá lớn.');const data=JSON.parse(await f.text());if(data.version!==1)throw Error('Sai phiên bản phiếu.');records={...records,...clean(data.records)};render();persist();$('adminStatus').textContent=storageOK?'Đã nhập và lưu phiếu duyệt.':'Đã nhập vào phiên này; cần xuất JSON để giữ lại.';}catch{$('adminStatus').textContent='Không nhập được. Hãy chọn tệp JSON xuất từ trang duyệt học liệu.';}e.target.value='';});
window.addEventListener('pagehide',()=>$('reviewAudio').pause());render();
})();
