-- Focused new-feature smoke, all synthetic rows/audits rolled back. No Auth mutation.
begin;
create temporary table hnh_authoring_smoke_report(check_name text,passed boolean) on commit drop;
do $smoke$
declare admin_id uuid; student_id uuid; g jsonb; body jsonb; preview jsonb; committed jsonb; result jsonb; bank jsonb; definition jsonb; attempt jsonb; row_id uuid; denied boolean; before_questions integer; before_audits integer;
begin
 select user_id into admin_id from public.profiles where role='ADMIN' and status='APPROVED' limit 1;
 select user_id into student_id from public.profiles where role='STUDENT' and status='APPROVED' limit 1;
 if admin_id is null or student_id is null then raise exception 'AUTHORING_SMOKE_REQUIRES_EXISTING_APPROVED_IDENTITIES'; end if;
 insert into public.courses(id,title,level,program) values('__authoring_smoke_course','Synthetic authoring smoke',1,'HSKK');
 insert into public.lesson_content(id,course_id,level,lesson_no,title_zh,title_vi,content) values('__authoring_smoke_lesson','__authoring_smoke_course',1,1,'测试','Synthetic authoring smoke','{}');
 insert into public.enrollments(user_id,course_id) values(student_id,'__authoring_smoke_course');
 insert into public.student_lesson_access(user_id,lesson_id) values(student_id,'__authoring_smoke_lesson');
 select count(*) into before_questions from public.assignment_question_versions;
 select count(*) into before_audits from public.audit_logs;
 perform set_config('request.jwt.claim.sub','',true);
 execute 'set local role anon';
 denied:=false;begin perform public.assignment_authoring('bank','{}');exception when insufficient_privilege then denied:=true;end;
 if not denied then raise exception 'AUTHORING_ANON_EXECUTE_GRANTED'; end if;
 execute 'reset role';
 perform set_config('request.jwt.claim.sub',student_id::text,true);
 execute 'set local role authenticated';
 denied:=false;begin perform public.assignment_authoring('bank','{}');exception when insufficient_privilege then denied:=true;end;
 if not denied then raise exception 'AUTHORING_STUDENT_READ_GRANTED'; end if;
 denied:=false;begin perform public.assignment_authoring('import_commit','{}');exception when insufficient_privilege then denied:=true;end;
 if not denied then raise exception 'AUTHORING_STUDENT_WRITE_GRANTED'; end if;
 denied:=false;begin perform * from account_internal.assignment_question_sources;exception when insufficient_privilege then denied:=true;end;
 if not denied then raise exception 'AUTHORING_PRIVATE_METADATA_EXPOSED'; end if;
 execute 'reset role';
 insert into hnh_authoring_smoke_report values('new RPC / private metadata permission boundary',true);
 perform set_config('request.jwt.claim.sub',admin_id::text,true);
 execute 'set local role authenticated';
 g:='{"lesson_id":"__authoring_smoke_lesson","question_key":"number17","kind":"mcq","prompt":"Chọn cách viết bằng chữ Hán của số 17.","options":[{"id":"A","text":"十七"},{"id":"B","text":"十六"},{"id":"C","text":"十八"},{"id":"D","text":"二十七"}],"answer_key":{"value":"A"}}';
 body:=jsonb_build_object('request_id',gen_random_uuid(),'lesson_id','__authoring_smoke_lesson','source',jsonb_build_object('source','synthetic_smoke','source_identifier','fixture:authoring','source_revision','1'),'questions',jsonb_build_array((g-'lesson_id')||jsonb_build_object('source_item_id','original-q1','generator',jsonb_build_object('rule','number','target','17','rule_version','zh-closed-1'))));
 preview:=public.assignment_authoring('import_preview',body);
 if preview->>'count'<>'1' or (select count(*) from public.assignment_question_versions)<>before_questions or (select count(*) from public.audit_logs)<>before_audits then raise exception 'AUTHORING_PREVIEW_MUTATED_QUESTIONS'; end if;
 committed:=public.assignment_authoring('import_commit',body);
 result:=public.assignment_authoring('import_commit',body);
 if result->>'already_imported'<>'true' or result->'questions'<>committed->'questions' then raise exception 'AUTHORING_RETRY_DUPLICATED'; end if;
 row_id:=(committed->'questions'->0->>'id')::uuid;
 bank:=public.assignment_authoring('bank','{"lesson_id":"__authoring_smoke_lesson"}');
 if bank->'questions'->0->'provenance'->>'source_item_id'<>'original-q1' or bank->'questions'->0->'provenance'->>'imported_by'<>admin_id::text or bank->'questions'->0->'provenance'->>'imported_at' is null or bank->'questions'->0->'provenance'->>'import_request_id'<>body->>'request_id' then raise exception 'AUTHORING_PROVENANCE_MISSING'; end if;
 denied:=false;begin perform public.assignment_command('question_create',g||'{"answer_key":{"value":"B"}}');exception when raise_exception then if SQLERRM='GENERATOR_KEY_CHANGED' then denied:=true;else raise;end if;end;
 if not denied then raise exception 'AUTHORING_RAW_KEY_CHANGE_BYPASSED_RULE'; end if;
 execute 'reset role';
 if (select count(*) from public.assignment_question_versions)<>before_questions+1 then raise exception 'AUTHORING_VERSION_COUNT_WRONG'; end if;
 insert into hnh_authoring_smoke_report values('preview / atomic import / replay / source / final generated set',true);
 perform set_config('request.jwt.claim.sub',admin_id::text,true);
 execute 'set local role authenticated';
 definition:=public.assignment_command('definition_create',jsonb_build_object('lesson_id','__authoring_smoke_lesson','title','Synthetic historical definition','question_version_ids',jsonb_build_array(row_id)));
 perform public.assignment_command('definition_preview',jsonb_build_object('version_id',definition->>'id'));
 perform public.assignment_command('definition_publish',jsonb_build_object('version_id',definition->>'id'));
 perform public.assignment_command('enable','{"lesson_id":"__authoring_smoke_lesson","enabled":true}');
 body:=jsonb_build_object('request_id',gen_random_uuid(),'question_version_id',row_id,'archived',true,'revision',0,'reason','Synthetic retirement');
 result:=public.assignment_authoring('archive',body);
 if public.assignment_authoring('archive',body)<>result then raise exception 'AUTHORING_ARCHIVE_REPLAY_CHANGED'; end if;
 if jsonb_array_length(public.assignment_authoring('bank','{"lesson_id":"__authoring_smoke_lesson"}')->'questions')<>0 then raise exception 'AUTHORING_ARCHIVE_FILTER_FAILED'; end if;
 denied:=false;begin perform public.assignment_command('definition_create',jsonb_build_object('lesson_id','__authoring_smoke_lesson','title','Blocked new definition','question_version_ids',jsonb_build_array(row_id)));exception when raise_exception then if SQLERRM='QUESTION_ARCHIVED' then denied:=true;else raise;end if;end;
 if not denied then raise exception 'AUTHORING_ARCHIVE_NEW_MEMBERSHIP_ALLOWED'; end if;
 execute 'reset role';
 perform set_config('request.jwt.claim.sub',student_id::text,true);
 execute 'set local role authenticated';
 attempt:=public.assignment_command('start',jsonb_build_object('lesson_id','__authoring_smoke_lesson','request_id',gen_random_uuid()));
 if attempt->'answers'->0->'question'->>'id'<>row_id::text or attempt::text like '%provenance%' or attempt::text like '%generator%' or attempt::text like '%answer_key%' then raise exception 'AUTHORING_OLD_PUBLISHED_PROJECTION_REGRESSION'; end if;
 execute 'reset role';
 denied:=false;begin update account_internal.assignment_question_sources set source='forged' where question_version_id=row_id;exception when raise_exception then if SQLERRM='AUTHORING_HISTORY_IMMUTABLE' then denied:=true;else raise;end if;end;
 if not denied then raise exception 'AUTHORING_SOURCE_MUTABLE'; end if;
 denied:=false;begin update account_internal.assignment_question_archive_events set archived=false where question_version_id=row_id;exception when raise_exception then if SQLERRM='AUTHORING_HISTORY_IMMUTABLE' then denied:=true;else raise;end if;end;
 if not denied then raise exception 'AUTHORING_ARCHIVE_HISTORY_MUTABLE'; end if;
 insert into hnh_authoring_smoke_report values('archive / old published references / private student projection / immutable history',true);
end$smoke$;
select * from hnh_authoring_smoke_report order by check_name;
rollback;
